/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const wasm_bindgen__closure__destroy__h040c1bffdd17099d: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h14abb28d551c279b: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h4925f7252eb078cd: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hef4e32109f14e796: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h3813c1554b688945: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h568af11bdd945dd0: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3a74389ac920630a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3a74389ac920630a_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3a74389ac920630a_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3a74389ac920630a_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3a74389ac920630a_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3a74389ac920630a_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3a74389ac920630a_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3a74389ac920630a_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hc5773ae4ed44845e: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h23d3c45056462102: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h23d3c45056462102_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h577683f21d4ab945: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hc1fa02a3fe2c6c31: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
